CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_DONGLE_SCREEN_IDLE_TIMEOUT_S=600
CONFIG_DONGLE_SCREEN_MAX_BRIGHTNESS=10
CONFIG_DONGLE_SCREEN_MIN_BRIGHTNESS=0
CONFIG_DONGLE_SCREEN_BRIGHTNESS_KEYBOARD_CONTROL=y
CONFIG_DONGLE_SCREEN_BRIGHTNESS_UP_KEYCODE=115
CONFIG_DONGLE_SCREEN_BRIGHTNESS_DOWN_KEYCODE=114
CONFIG_DONGLE_SCREEN_BRIGHTNESS_STEP=5

# BLE central 동작
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# 동글: BLE central 모드 안정화 설정
CONFIG_BT=y
CONFIG_BT_MAX_CONN=4

CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_GATT_CLIENT=y         
CONFIG_BT_OBSERVER=y
CONFIG_BT_CENTRAL=y
